### PR TITLE
Be a little more lenient in where to find bash

### PR DESCRIPTION
**Pull request by lmanul**

### CODE REVIEW

**Comment by grandchild** [comment]
Thanks :)

**Comment by lmanul** [comment]
You're very welcome! Thanks for making this. It still doesn't quite work for me yet so I might spend a little more time making it work in my environment and see if it makes sense to send that back to you too :-)

**Comment by grandchild** [comment]
Wait a few minutes, I'm working on making it work with awesome 4+. As is here, it only works with awesome 3.5.

**Comment by lmanul** [comment]
Ah yes that's probably my issue. No rush at all :-) Thanks!

**Comment by grandchild** [comment]
There you go :)

**Comment by lmanul** [comment]
That works perfectly for me now. Thanks!

**Comment by grandchild** [comment]
And for me, haven't been using it since the update to awesome 4.0, so thanks for the poke :P

**Pull request merged**
